name: 'replace md images'
description: 'replace images in markdown to tencent cloud cos url'
inputs:
  token:
    description: 'github token'
    default: ${{ github.token }}
    required: true
outputs:
  content:
    description: 'replaced markdown'
runs:
  using: 'node16'
  main: 'dist/index.js'